export const filterFormDefaultConfig = {
  supplier: {
    id: '',
    name: '',
    isSelected: false,
  },
  tradeMark: '',
  isDelivery: true,
  isPickup: true,
  inStock: false,
  withImages: false,
  hasDiscount: false,
  features: [],
  featuresData: [],
  priceFrom: null,
  priceTo: null,
  location: {
    fias: '',
    name: '',
    isSelected: false,
  },
  categorySearchQuery: '',
  subCategoryId: '',
  categoryId: '',
};
