export enum MetrikaEventModel {
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_PUT = 'ORDER_PUT',
  ORDER_TRY = 'TRY_ORDER',
  PRICEREQUEST_CREATE = 'PRICEREQUEST_CREATE',
  ORG_REGISTER = 'ORG_REGISTER',
}
